### ISSUE TITLE
Does this project have a license?

### ISSUE THREAD

**Issue by larsiusprime** [stevebob/roguelike-lighting-demo#1]
Hey there! I've been going through some roguelike tutorials and I came across your sample code and am doing some exercises based off of it. Sometimes I like to use the results of such studies in future projects, but I wanted to check with you first if that's okay as I didn't notice any particular license on this repo. Can you confirm what terms this code is available under? 

Thanks for writing and sharing this!

**Comment by stevebob** [comment]
Code is available under MIT license. It was in the package.json file, but I just explicitly added a LICENSE file to clarify.
